// This file is auto-generated by @hey-api/openapi-ts

export const AccountReadSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Name",
    },
    last_name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Last Name",
    },
    status: {
      $ref: "#/components/schemas/AccountStatus",
    },
    ob_status: {
      $ref: "#/components/schemas/OnboardingStatus",
    },
    country: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Country",
    },
    person_type: {
      $ref: "#/components/schemas/PersonType",
    },
  },
  type: "object",
  required: ["id", "status", "ob_status", "person_type"],
  title: "AccountRead",
} as const;

export const AccountStatusSchema = {
  type: "string",
  enum: ["CREATED", "VERIFYING", "ACTIVE", "DELETED"],
  title: "AccountStatus",
} as const;

export const AddressUSSchema = {
  properties: {
    street_line_1: {
      type: "string",
      title: "Street Line 1",
    },
    street_line_2: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Street Line 2",
    },
    city: {
      type: "string",
      title: "City",
    },
    country: {
      type: "string",
      enum: ["USA"],
      const: "USA",
      title: "Country",
    },
    state: {
      $ref: "#/components/schemas/USAState",
    },
    postal_code: {
      type: "string",
      title: "Postal Code",
    },
  },
  type: "object",
  required: ["street_line_1", "city", "country", "state", "postal_code"],
  title: "AddressUS",
} as const;

export const AssetDetailSchema = {
  properties: {
    change_percent: {
      type: "string",
      title: "Change Percent",
    },
    change: {
      type: "string",
      title: "Change",
    },
    close: {
      type: "string",
      title: "Close",
    },
    high: {
      type: "string",
      title: "High",
    },
    price: {
      type: "string",
      title: "Price",
    },
    low: {
      type: "string",
      title: "Low",
    },
    open: {
      type: "string",
      title: "Open",
    },
    previous_close: {
      type: "string",
      title: "Previous Close",
    },
    volume: {
      type: "string",
      title: "Volume",
    },
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Description",
    },
    symbol: {
      type: "string",
      title: "Symbol",
    },
    display_name: {
      type: "string",
      title: "Display Name",
    },
    logo_url: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Logo Url",
    },
    external_id: {
      type: "integer",
      title: "External Id",
    },
  },
  type: "object",
  required: [
    "change_percent",
    "change",
    "close",
    "high",
    "price",
    "low",
    "open",
    "previous_close",
    "volume",
    "id",
    "name",
    "symbol",
    "display_name",
    "external_id",
  ],
  title: "AssetDetail",
} as const;

export const AssetPriceSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Description",
    },
    symbol: {
      type: "string",
      title: "Symbol",
    },
    display_name: {
      type: "string",
      title: "Display Name",
    },
    logo_url: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Logo Url",
    },
    external_id: {
      type: "integer",
      title: "External Id",
    },
    price: {
      type: "string",
      title: "Price",
    },
  },
  type: "object",
  required: ["id", "name", "symbol", "display_name", "external_id", "price"],
  title: "AssetPrice",
} as const;

export const AssetsWithPriceSchema = {
  items: {
    $ref: "#/components/schemas/AssetPrice",
  },
  type: "array",
  title: "AssetsWithPrice",
} as const;

export const BalanceSchema = {
  properties: {
    available: {
      type: "string",
      title: "Available",
      default: "0",
    },
    pending: {
      type: "string",
      title: "Pending",
      default: "0",
    },
    portfolio_market_value: {
      type: "string",
      title: "Portfolio Market Value",
      default: "0",
    },
    equity: {
      type: "string",
      title: "Equity",
      readOnly: true,
    },
    portfolio_market_value_in_usd: {
      type: "string",
      title: "Portfolio Market Value In Usd",
      readOnly: true,
    },
    available_in_usd: {
      type: "string",
      title: "Available In Usd",
      readOnly: true,
    },
    pending_in_usd: {
      type: "string",
      title: "Pending In Usd",
      readOnly: true,
    },
    equity_in_usd: {
      type: "string",
      title: "Equity In Usd",
      readOnly: true,
    },
    precision: {
      type: "integer",
      title: "Precision",
      readOnly: true,
    },
  },
  type: "object",
  required: [
    "equity",
    "portfolio_market_value_in_usd",
    "available_in_usd",
    "pending_in_usd",
    "equity_in_usd",
    "precision",
  ],
  title: "Balance",
} as const;

export const BankSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    institution_name: {
      type: "string",
      title: "Institution Name",
    },
    country: {
      type: "string",
      title: "Country",
    },
    currency: {
      type: "string",
      title: "Currency",
    },
    bank_code: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Bank Code",
    },
    transfer_code: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Transfer Code",
    },
    payout_method_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Payout Method Id",
    },
    created_at: {
      type: "string",
      format: "date-time",
      title: "Created At",
    },
    updated_at: {
      type: "string",
      format: "date-time",
      title: "Updated At",
    },
  },
  type: "object",
  required: ["name", "institution_name", "country", "currency"],
  title: "Bank",
} as const;

export const BankAccountTypeSchema = {
  type: "string",
  enum: ["savings", "checking"],
  title: "BankAccountType",
} as const;

export const BankCodeCOSchema = {
  type: "string",
  enum: [
    "co_bogota",
    "co_bancolombia",
    "co_daviplata",
    "co_nequi",
    "co_lulo_bank_sa",
    "co_falabella",
    "co_davivienda",
    "co_bbva",
    "co_global66",
  ],
  title: "BankCodeCO",
} as const;

export const BeneficiaryLatamSchema = {
  properties: {
    person_type: {
      $ref: "#/components/schemas/PersonType",
    },
    tax_identification: {
      type: "string",
      title: "Tax Identification",
    },
    email: {
      type: "string",
      title: "Email",
    },
  },
  type: "object",
  required: ["person_type", "tax_identification", "email"],
  title: "BeneficiaryLatam",
} as const;

export const BeneficiaryUSSchema = {
  properties: {
    person_type: {
      $ref: "#/components/schemas/PersonType",
    },
    first_name: {
      type: "string",
      title: "First Name",
    },
    last_name: {
      type: "string",
      title: "Last Name",
    },
  },
  type: "object",
  required: ["person_type", "first_name", "last_name"],
  title: "BeneficiaryUS",
} as const;

export const CountrySchema = {
  type: "string",
  enum: ["USA", "COL", "MEX", "BRA", "ARG", "PAN"],
  title: "Country",
} as const;

export const CountryBaseSchema = {
  properties: {
    name_iso: {
      type: "string",
      title: "Name Iso",
    },
    code_2: {
      type: "string",
      title: "Code 2",
    },
    code_3: {
      type: "string",
      title: "Code 3",
    },
    currency: {
      type: "string",
      title: "Currency",
    },
    is_supported: {
      type: "boolean",
      title: "Is Supported",
    },
  },
  type: "object",
  required: ["name_iso", "code_2", "code_3", "currency", "is_supported"],
  title: "CountryBase",
} as const;

export const CurrencySchema = {
  type: "string",
  enum: ["USD", "COP", "EUR", "MXN", "BRL", "ARS"],
  title: "Currency",
} as const;

export const ExternalAccountBRSchema = {
  properties: {
    account_name: {
      type: "string",
      title: "Account Name",
    },
    pix_key: {
      type: "string",
      title: "Pix Key",
    },
  },
  type: "object",
  required: ["account_name", "pix_key"],
  title: "ExternalAccountBR",
} as const;

export const ExternalAccountLatamSchema = {
  properties: {
    account_name: {
      type: "string",
      title: "Account Name",
    },
    account_number: {
      type: "string",
      title: "Account Number",
    },
    account_type: {
      $ref: "#/components/schemas/BankAccountType",
    },
    bank_code: {
      $ref: "#/components/schemas/BankCodeCO",
    },
    beneficiary: {
      $ref: "#/components/schemas/BeneficiaryLatam",
    },
  },
  type: "object",
  required: [
    "account_name",
    "account_number",
    "account_type",
    "bank_code",
    "beneficiary",
  ],
  title: "ExternalAccountLatam",
} as const;

export const ExternalAccountReadSimpleSchema = {
  properties: {
    account_number: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Account Number",
    },
  },
  type: "object",
  required: ["account_number"],
  title: "ExternalAccountReadSimple",
} as const;

export const ExternalAccountUSSchema = {
  properties: {
    bank_name: {
      type: "string",
      title: "Bank Name",
    },
    account_name: {
      type: "string",
      title: "Account Name",
    },
    account_number: {
      type: "string",
      title: "Account Number",
    },
    routing_number: {
      type: "string",
      title: "Routing Number",
    },
    account_type: {
      $ref: "#/components/schemas/BankAccountType",
    },
    beneficiary: {
      $ref: "#/components/schemas/BeneficiaryUS",
    },
    address: {
      $ref: "#/components/schemas/AddressUS",
    },
    idempotency_key: {
      type: "string",
      format: "uuid",
      title: "Idempotency Key",
    },
  },
  type: "object",
  required: [
    "bank_name",
    "account_name",
    "account_number",
    "routing_number",
    "account_type",
    "beneficiary",
    "address",
  ],
  title: "ExternalAccountUS",
} as const;

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: "#/components/schemas/ValidationError",
      },
      type: "array",
      title: "Detail",
    },
  },
  type: "object",
  title: "HTTPValidationError",
} as const;

export const KYCStatusSchema = {
  type: "string",
  enum: ["NOT_STARTED", "APPROVED", "REJECTED", "PENDING", "INCOMPLETE"],
  title: "KYCStatus",
} as const;

export const KycStatusResponseSchema = {
  properties: {
    status: {
      $ref: "#/components/schemas/KYCStatus",
    },
    attempted_dt: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
      title: "Attempted Dt",
    },
  },
  type: "object",
  required: ["status"],
  title: "KycStatusResponse",
} as const;

export const MarketHoursSchema = {
  properties: {
    is_market_open: {
      type: "boolean",
      title: "Is Market Open",
    },
    current_session_close_dt: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
      title: "Current Session Close Dt",
    },
    current_session_open_dt: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
      title: "Current Session Open Dt",
    },
    next_session_close_dt: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
      title: "Next Session Close Dt",
    },
    next_session_open_dt: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
      title: "Next Session Open Dt",
    },
  },
  type: "object",
  required: [
    "is_market_open",
    "current_session_close_dt",
    "current_session_open_dt",
    "next_session_close_dt",
    "next_session_open_dt",
  ],
  title: "MarketHours",
} as const;

export const MyAssetSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    symbol: {
      type: "string",
      title: "Symbol",
    },
    name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Name",
    },
    display_name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Display Name",
    },
    logo_url: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Logo Url",
    },
    quantity_in_wei: {
      type: "integer",
      title: "Quantity In Wei",
    },
    external_id: {
      type: "integer",
      title: "External Id",
    },
    equity: {
      type: "integer",
      title: "Equity",
    },
    equity_in_usd: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Equity In Usd",
    },
    change_percent: {
      type: "string",
      title: "Change Percent",
    },
  },
  type: "object",
  required: [
    "symbol",
    "quantity_in_wei",
    "external_id",
    "equity",
    "change_percent",
  ],
  title: "MyAsset",
} as const;

export const MyAssetLiteSchema = {
  properties: {
    symbol: {
      type: "string",
      title: "Symbol",
    },
    quantity_in_wei: {
      type: "integer",
      title: "Quantity In Wei",
    },
    external_id: {
      type: "integer",
      title: "External Id",
    },
  },
  type: "object",
  required: ["symbol", "quantity_in_wei", "external_id"],
  title: "MyAssetLite",
} as const;

export const MyAssetsSchema = {
  items: {
    $ref: "#/components/schemas/MyAsset",
  },
  type: "array",
  title: "MyAssets",
} as const;

export const OBKYCStatusResponseSchema = {
  properties: {
    ob_status: {
      $ref: "#/components/schemas/OnboardingStatus",
    },
    kyc_status: {
      $ref: "#/components/schemas/KycStatusResponse",
    },
  },
  type: "object",
  required: ["ob_status", "kyc_status"],
  title: "OBKYCStatusResponse",
} as const;

export const OnboardingAddressStepSchema = {
  properties: {
    street_line_1: {
      type: "string",
      title: "Street Line 1",
    },
    street_line_2: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Street Line 2",
    },
    city: {
      type: "string",
      title: "City",
    },
    state: {
      type: "string",
      title: "State",
    },
    postal_code: {
      type: "string",
      title: "Postal Code",
    },
  },
  type: "object",
  required: ["street_line_1", "city", "state", "postal_code"],
  title: "OnboardingAddressStep",
} as const;

export const OnboardingCountryStepSchema = {
  properties: {
    country: {
      type: "string",
      maxLength: 2,
      minLength: 2,
      pattern: "^[A-Z]{2}$",
      title: "Country",
      description: "ISO 2-letter country code",
    },
  },
  type: "object",
  required: ["country"],
  title: "OnboardingCountryStep",
} as const;

export const OnboardingNamesStepSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
    },
    last_name: {
      type: "string",
      title: "Last Name",
    },
  },
  type: "object",
  required: ["name", "last_name"],
  title: "OnboardingNamesStep",
} as const;

export const OnboardingStatusSchema = {
  type: "string",
  enum: [
    "NOT_STARTED",
    "NAMES_STEP",
    "COUNTRY_STEP",
    "ADDRESS_STEP",
    "KYC_PROVIDER_STEP",
  ],
  title: "OnboardingStatus",
} as const;

export const OrderSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    transaction_hash: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Transaction Hash",
    },
    external_id: {
      type: "string",
      title: "External Id",
    },
    symbol: {
      type: "string",
      title: "Symbol",
    },
    name: {
      type: "string",
      title: "Name",
    },
    status: {
      $ref: "#/components/schemas/OrderStatus",
    },
    order_side: {
      $ref: "#/components/schemas/OrderSide",
    },
    order_type: {
      $ref: "#/components/schemas/OrderType",
    },
    fee_wei: {
      type: "integer",
      title: "Fee Wei",
    },
    fee: {
      type: "string",
      title: "Fee",
    },
    total_wei: {
      type: "integer",
      title: "Total Wei",
    },
    total: {
      type: "string",
      title: "Total",
    },
    asset_token_filled_wei: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Asset Token Filled Wei",
    },
    asset_token_filled: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Asset Token Filled",
    },
    payment_token_filled_wei: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Payment Token Filled Wei",
    },
    payment_token_filled: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Payment Token Filled",
    },
    created_at: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
      title: "Created At",
    },
    filled_at: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
      title: "Filled At",
    },
  },
  type: "object",
  required: [
    "transaction_hash",
    "external_id",
    "symbol",
    "name",
    "status",
    "order_side",
    "order_type",
    "fee_wei",
    "fee",
    "total_wei",
    "total",
    "asset_token_filled_wei",
    "asset_token_filled",
    "payment_token_filled_wei",
    "payment_token_filled",
    "created_at",
    "filled_at",
  ],
  title: "Order",
} as const;

export const OrderQuoteSchema = {
  properties: {
    id: {
      anyOf: [
        {
          type: "string",
          format: "uuid",
        },
        {
          type: "null",
        },
      ],
      title: "Id",
    },
    external_order_id: {
      type: "string",
      title: "External Order Id",
    },
    asset_id: {
      type: "string",
      format: "uuid",
      title: "Asset Id",
    },
    side: {
      $ref: "#/components/schemas/OrderSide",
    },
    order_type: {
      $ref: "#/components/schemas/OrderType",
    },
    quantity: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Quantity",
    },
    amount_in: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Amount In",
    },
    amount_out: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Amount Out",
    },
    asset_price: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Asset Price",
    },
    fee: {
      type: "integer",
      title: "Fee",
    },
    partner_fee: {
      type: "integer",
      title: "Partner Fee",
    },
    zeneca_fee: {
      type: "integer",
      title: "Zeneca Fee",
    },
    total_amount: {
      type: "integer",
      title: "Total Amount",
    },
    user_address: {
      type: "string",
      title: "User Address",
    },
    signature: {
      type: "string",
      title: "Signature",
    },
    chain_id: {
      type: "integer",
      title: "Chain Id",
    },
    order_data: {
      $ref: "#/components/schemas/OrderQuoteData",
    },
    transactions: {
      anyOf: [
        {
          items: {
            $ref: "#/components/schemas/Transaction",
          },
          type: "array",
        },
        {
          type: "null",
        },
      ],
      title: "Transactions",
    },
    deadline: {
      type: "integer",
      title: "Deadline",
    },
    precision: {
      type: "integer",
      title: "Precision",
      readOnly: true,
    },
    fee_displayed: {
      type: "string",
      title: "Fee Displayed",
      description: `Convert fee from USDC wei (6 decimals) to Decimal with 2 decimal places.

Example:
    fee = 1234567 (1.234567 USDC in wei)
    returns Decimal('1.23') (rounded to 2 decimal places)`,
      readOnly: true,
    },
    total_amount_displayed: {
      type: "string",
      title: "Total Amount Displayed",
      description: `Convert fee from USDC wei (6 decimals) to Decimal with 2 decimal places.

Example:
    fee = 1234567 (1.234567 USDC in wei)
    returns Decimal('1.23') (rounded to 2 decimal places)`,
      readOnly: true,
    },
  },
  type: "object",
  required: [
    "external_order_id",
    "asset_id",
    "side",
    "order_type",
    "fee",
    "partner_fee",
    "zeneca_fee",
    "total_amount",
    "user_address",
    "signature",
    "chain_id",
    "order_data",
    "deadline",
    "precision",
    "fee_displayed",
    "total_amount_displayed",
  ],
  title: "OrderQuote",
} as const;

export const OrderQuoteDataSchema = {
  properties: {
    signature: {
      type: "string",
      title: "Signature",
    },
    external_order_id: {
      type: "string",
      title: "External Order Id",
    },
    created_at: {
      type: "integer",
      title: "Created At",
    },
    deadline: {
      type: "integer",
      title: "Deadline",
    },
    recipient: {
      type: "string",
      title: "Recipient",
    },
    allowance_amount: {
      type: "integer",
      title: "Allowance Amount",
    },
    tif: {
      type: "integer",
      title: "Tif",
    },
    fee: {
      type: "string",
      title: "Fee",
    },
    sell: {
      type: "boolean",
      title: "Sell",
    },
    asset_token_quantity: {
      type: "integer",
      title: "Asset Token Quantity",
    },
    payment_token_quantity: {
      type: "integer",
      title: "Payment Token Quantity",
    },
    asset_token: {
      type: "string",
      title: "Asset Token",
    },
    payment_token: {
      type: "string",
      title: "Payment Token",
    },
    order_type: {
      type: "integer",
      title: "Order Type",
    },
    limit_price: {
      type: "integer",
      title: "Limit Price",
    },
    request_timestamp: {
      type: "integer",
      title: "Request Timestamp",
    },
  },
  type: "object",
  required: [
    "signature",
    "external_order_id",
    "created_at",
    "deadline",
    "recipient",
    "allowance_amount",
    "tif",
    "fee",
    "sell",
    "asset_token_quantity",
    "payment_token_quantity",
    "asset_token",
    "payment_token",
    "order_type",
    "limit_price",
    "request_timestamp",
  ],
  title: "OrderQuoteData",
} as const;

export const OrderQuoteRequestSchema = {
  properties: {
    asset_id: {
      type: "string",
      format: "uuid",
      title: "Asset Id",
    },
    side: {
      $ref: "#/components/schemas/OrderSide",
    },
    order_type: {
      $ref: "#/components/schemas/OrderType",
    },
    quantity: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Quantity",
      default: 0,
    },
    amount: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Amount",
      default: 0,
    },
    limit_price: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Limit Price",
      default: 0,
    },
  },
  type: "object",
  required: ["asset_id", "side", "order_type"],
  title: "OrderQuoteRequest",
} as const;

export const OrderSideSchema = {
  type: "string",
  enum: ["BUY", "SELL"],
  title: "OrderSide",
} as const;

export const OrderStatusSchema = {
  type: "string",
  enum: [
    "PENDING",
    "PENDING_SUBMIT",
    "PENDING_CANCEL",
    "PENDING_ESCROW",
    "PENDING_FILL",
    "ESCROWED",
    "SUBMITTED",
    "CANCELLED",
    "FILLED",
    "ERROR",
    "REJECTED",
    "REQUIRING_CONTACT",
  ],
  title: "OrderStatus",
} as const;

export const OrderTypeSchema = {
  type: "string",
  enum: ["MARKET", "LIMIT"],
  title: "OrderType",
} as const;

export const PaymentRailSchema = {
  type: "string",
  enum: ["ach", "ach_push", "wire", "sepa"],
  title: "PaymentRail",
} as const;

export const PersonTypeSchema = {
  type: "string",
  enum: ["individual", "business"],
  title: "PersonType",
} as const;

export const QuoteReadSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    source: {
      type: "string",
      title: "Source",
    },
    destination: {
      type: "string",
      title: "Destination",
    },
    amount_in: {
      type: "integer",
      title: "Amount In",
    },
    amount_out: {
      type: "integer",
      title: "Amount Out",
    },
    exchange_rate: {
      type: "integer",
      title: "Exchange Rate",
    },
    expires_at: {
      type: "integer",
      title: "Expires At",
    },
    network_fee: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Network Fee",
    },
    zeneca_fee: {
      type: "integer",
      title: "Zeneca Fee",
    },
    fee: {
      type: "integer",
      title: "Fee",
    },
    external_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "External Id",
    },
    recipient_id: {
      anyOf: [
        {
          type: "string",
          format: "uuid",
        },
        {
          type: "null",
        },
      ],
      title: "Recipient Id",
    },
  },
  type: "object",
  required: [
    "id",
    "source",
    "destination",
    "amount_in",
    "amount_out",
    "exchange_rate",
    "expires_at",
    "network_fee",
    "zeneca_fee",
    "fee",
    "external_id",
    "recipient_id",
  ],
  title: "QuoteRead",
} as const;

export const QuoteRequestSchema = {
  properties: {
    recipient_id: {
      anyOf: [
        {
          type: "string",
          format: "uuid",
        },
        {
          type: "null",
        },
      ],
      title: "Recipient Id",
    },
    source: {
      anyOf: [
        {
          $ref: "#/components/schemas/TokenSymbol",
        },
        {
          $ref: "#/components/schemas/Currency",
        },
      ],
      title: "Source",
    },
    destination: {
      anyOf: [
        {
          $ref: "#/components/schemas/TokenSymbol",
        },
        {
          $ref: "#/components/schemas/Currency",
        },
      ],
      title: "Destination",
    },
    amount_in: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Amount In",
    },
    amount_out: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Amount Out",
    },
    payment_rail: {
      anyOf: [
        {
          $ref: "#/components/schemas/PaymentRail",
        },
        {
          type: "null",
        },
      ],
    },
  },
  type: "object",
  required: ["recipient_id", "source", "destination"],
  title: "QuoteRequest",
} as const;

export const RecipientReadSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    owner: {
      type: "boolean",
      title: "Owner",
    },
    country: {
      anyOf: [
        {
          $ref: "#/components/schemas/Country",
        },
        {
          type: "null",
        },
      ],
    },
  },
  type: "object",
  required: ["id", "name", "owner"],
  title: "RecipientRead",
} as const;

export const RecipientReadWithExternalAccountSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    owner: {
      type: "boolean",
      title: "Owner",
    },
    country: {
      anyOf: [
        {
          $ref: "#/components/schemas/Country",
        },
        {
          type: "null",
        },
      ],
    },
    external_account: {
      $ref: "#/components/schemas/ExternalAccountReadSimple",
    },
  },
  type: "object",
  required: ["id", "name", "owner", "external_account"],
  title: "RecipientReadWithExternalAccount",
} as const;

export const RecipientRequestSchema = {
  oneOf: [
    {
      $ref: "#/components/schemas/RecipientRequestLatam",
    },
    {
      $ref: "#/components/schemas/RecipientRequestBR",
    },
    {
      $ref: "#/components/schemas/RecipientRequestUS",
    },
  ],
  title: "RecipientRequest",
  discriminator: {
    propertyName: "country",
    mapping: {
      ARG: "#/components/schemas/RecipientRequestLatam",
      BRA: "#/components/schemas/RecipientRequestBR",
      COL: "#/components/schemas/RecipientRequestLatam",
      MEX: "#/components/schemas/RecipientRequestLatam",
      USA: "#/components/schemas/RecipientRequestUS",
    },
  },
} as const;

export const RecipientRequestBRSchema = {
  properties: {
    name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Name",
    },
    country: {
      type: "string",
      enum: ["BRA"],
      const: "BRA",
      title: "Country",
    },
    owner: {
      type: "boolean",
      title: "Owner",
    },
    external_account: {
      $ref: "#/components/schemas/ExternalAccountBR",
    },
    customer_id: {
      type: "string",
      format: "uuid",
      title: "Customer Id",
    },
  },
  type: "object",
  required: ["name", "country", "owner", "external_account", "customer_id"],
  title: "RecipientRequestBR",
} as const;

export const RecipientRequestLatamSchema = {
  properties: {
    name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Name",
    },
    country: {
      type: "string",
      enum: ["COL", "MEX", "ARG"],
      title: "Country",
    },
    owner: {
      type: "boolean",
      title: "Owner",
    },
    external_account: {
      $ref: "#/components/schemas/ExternalAccountLatam",
    },
    customer_id: {
      type: "string",
      format: "uuid",
      title: "Customer Id",
    },
  },
  type: "object",
  required: ["name", "country", "owner", "external_account", "customer_id"],
  title: "RecipientRequestLatam",
} as const;

export const RecipientRequestUSSchema = {
  properties: {
    name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Name",
    },
    country: {
      type: "string",
      enum: ["USA"],
      const: "USA",
      title: "Country",
    },
    owner: {
      type: "boolean",
      title: "Owner",
    },
    external_account: {
      $ref: "#/components/schemas/ExternalAccountUS",
    },
    customer_id: {
      type: "string",
      format: "uuid",
      title: "Customer Id",
    },
  },
  type: "object",
  required: ["name", "country", "owner", "external_account", "customer_id"],
  title: "RecipientRequestUS",
} as const;

export const StockTickDataSchema = {
  properties: {
    close: {
      type: "string",
      title: "Close",
    },
    high: {
      type: "string",
      title: "High",
    },
    low: {
      type: "string",
      title: "Low",
    },
    open: {
      type: "string",
      title: "Open",
    },
    timestamp: {
      type: "integer",
      title: "Timestamp",
    },
  },
  type: "object",
  required: ["close", "high", "low", "open", "timestamp"],
  title: "StockTickData",
} as const;

export const StockTickDataListSchema = {
  items: {
    $ref: "#/components/schemas/StockTickData",
  },
  type: "array",
  title: "StockTickDataList",
} as const;

export const TimespanSchema = {
  type: "string",
  enum: ["DAY", "WEEK", "MONTH", "YEAR"],
  title: "Timespan",
} as const;

export const TokenSymbolSchema = {
  type: "string",
  enum: ["usdc.polygon", "usdc.base", "usdc.stellar"],
  title: "TokenSymbol",
} as const;

export const TransactionSchema = {
  properties: {
    to: {
      type: "string",
      title: "To",
    },
    data: {
      type: "string",
      title: "Data",
    },
    value: {
      type: "integer",
      title: "Value",
    },
  },
  type: "object",
  required: ["to", "data", "value"],
  title: "Transaction",
} as const;

export const TransferReadSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    withdrawal: {
      anyOf: [
        {
          $ref: "#/components/schemas/WithdrawalRead",
        },
        {
          type: "null",
        },
      ],
    },
    recipient: {
      anyOf: [
        {
          $ref: "#/components/schemas/RecipientRead",
        },
        {
          type: "null",
        },
      ],
    },
    quote: {
      anyOf: [
        {
          $ref: "#/components/schemas/QuoteRead",
        },
        {
          type: "null",
        },
      ],
    },
    deposit_id: {
      anyOf: [
        {
          type: "string",
          format: "uuid",
        },
        {
          type: "null",
        },
      ],
      title: "Deposit Id",
    },
    status: {
      $ref: "#/components/schemas/TransferStatus",
    },
    customer_id: {
      type: "string",
      format: "uuid",
      title: "Customer Id",
    },
    reference_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Reference Id",
    },
    recipient_id: {
      anyOf: [
        {
          type: "string",
          format: "uuid",
        },
        {
          type: "null",
        },
      ],
      title: "Recipient Id",
    },
    created_at: {
      type: "string",
      format: "date-time",
      title: "Created At",
    },
  },
  type: "object",
  required: ["id", "status", "customer_id", "created_at"],
  title: "TransferRead",
} as const;

export const TransferRequestSchema = {
  properties: {
    quote_id: {
      type: "string",
      format: "uuid",
      title: "Quote Id",
    },
    customer_id: {
      type: "string",
      format: "uuid",
      title: "Customer Id",
    },
    recipient_id: {
      type: "string",
      format: "uuid",
      title: "Recipient Id",
    },
    reference_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Reference Id",
    },
  },
  type: "object",
  required: ["quote_id", "customer_id", "recipient_id"],
  title: "TransferRequest",
} as const;

export const TransferStatusSchema = {
  type: "string",
  enum: [
    "WAITING",
    "PAID",
    "PENDING",
    "SUBMITTED",
    "IN_PROGRESS",
    "SENT",
    "REJECTED",
    "INVALID_ACCOUNT_DETAILS",
    "ERROR",
  ],
  title: "TransferStatus",
} as const;

export const USAStateSchema = {
  type: "string",
  enum: [
    "US-AL",
    "US-AK",
    "US-AZ",
    "US-AR",
    "US-CA",
    "US-CO",
    "US-CT",
    "US-DE",
    "US-FL",
    "US-GA",
    "US-HI",
    "US-ID",
    "US-IL",
    "US-IN",
    "US-IA",
    "US-KS",
    "US-KY",
    "US-LA",
    "US-ME",
    "US-MD",
    "US-MA",
    "US-MI",
    "US-MN",
    "US-MS",
    "US-MO",
    "US-MT",
    "US-NE",
    "US-NV",
    "US-NH",
    "US-NJ",
    "US-NM",
    "US-NY",
    "US-NC",
    "US-ND",
    "US-OH",
    "US-OK",
    "US-OR",
    "US-PA",
    "US-RI",
    "US-SC",
    "US-SD",
    "US-TN",
    "US-TX",
    "US-UT",
    "US-VT",
    "US-VA",
    "US-WA",
    "US-WV",
    "US-WI",
    "US-WY",
  ],
  title: "USAState",
} as const;

export const UserSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Name",
    },
    email: {
      type: "string",
      title: "Email",
    },
    phone: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Phone",
    },
    has_third_party_auth: {
      type: "boolean",
      title: "Has Third Party Auth",
      default: false,
    },
    provider_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Provider Id",
    },
    created_at: {
      type: "string",
      format: "date-time",
      title: "Created At",
    },
  },
  type: "object",
  required: ["name", "email", "phone", "provider_id"],
  title: "User",
} as const;

export const UserCreateInSchema = {
  properties: {
    email: {
      type: "string",
      format: "email",
      title: "Email",
    },
    name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Name",
    },
    phone: {
      anyOf: [
        {
          type: "string",
          maxLength: 64,
          minLength: 7,
          format: "phone",
        },
        {
          type: "null",
        },
      ],
      title: "Phone",
    },
    wallet: {
      anyOf: [
        {
          $ref: "#/components/schemas/WalletCreateIn",
        },
        {
          type: "null",
        },
      ],
    },
    has_third_party_auth: {
      type: "boolean",
      title: "Has Third Party Auth",
      default: false,
    },
  },
  type: "object",
  required: ["email"],
  title: "UserCreateIn",
} as const;

export const UserReadSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Name",
    },
    email: {
      type: "string",
      title: "Email",
    },
    phone: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Phone",
    },
    has_third_party_auth: {
      type: "boolean",
      title: "Has Third Party Auth",
    },
    provider_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Provider Id",
    },
    wallets: {
      items: {
        $ref: "#/components/schemas/WalletRead",
      },
      type: "array",
      title: "Wallets",
    },
    account: {
      anyOf: [
        {
          $ref: "#/components/schemas/AccountRead",
        },
        {
          type: "null",
        },
      ],
    },
  },
  type: "object",
  required: [
    "id",
    "name",
    "email",
    "phone",
    "has_third_party_auth",
    "provider_id",
    "wallets",
    "account",
  ],
  title: "UserRead",
} as const;

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
        ],
      },
      type: "array",
      title: "Location",
    },
    msg: {
      type: "string",
      title: "Message",
    },
    type: {
      type: "string",
      title: "Error Type",
    },
  },
  type: "object",
  required: ["loc", "msg", "type"],
  title: "ValidationError",
} as const;

export const WalletCreateInSchema = {
  properties: {
    address: {
      type: "string",
      title: "Address",
    },
    smart_account_address: {
      type: "string",
      title: "Smart Account Address",
    },
  },
  type: "object",
  required: ["address", "smart_account_address"],
  title: "WalletCreateIn",
} as const;

export const WalletReadSchema = {
  properties: {
    address: {
      type: "string",
      title: "Address",
    },
    smart_account_address: {
      type: "string",
      title: "Smart Account Address",
    },
  },
  type: "object",
  required: ["address", "smart_account_address"],
  title: "WalletRead",
} as const;

export const WithdrawalReadSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
    },
    status: {
      $ref: "#/components/schemas/TransferStatus",
    },
    external_id: {
      type: "string",
      title: "External Id",
    },
    payout_address: {
      type: "string",
      title: "Payout Address",
    },
    payout_token: {
      type: "string",
      title: "Payout Token",
    },
    payout_network_id: {
      type: "string",
      title: "Payout Network Id",
    },
    tx_hash: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Tx Hash",
    },
    quote_id: {
      anyOf: [
        {
          type: "string",
          format: "uuid",
        },
        {
          type: "null",
        },
      ],
      title: "Quote Id",
    },
    created_at: {
      type: "string",
      format: "date-time",
      title: "Created At",
    },
    finished_at: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
      title: "Finished At",
    },
  },
  type: "object",
  required: [
    "id",
    "status",
    "external_id",
    "payout_address",
    "payout_token",
    "payout_network_id",
    "created_at",
  ],
  title: "WithdrawalRead",
} as const;
