// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { LoginLoginOrCreateData, LoginLoginOrCreateError, LoginLoginOrCreateResponse, QuotesCreateQuoteData, QuotesCreateQuoteError, QuotesCreateQuoteResponse, QuotesGetQuoteData, QuotesGetQuoteError, QuotesGetQuoteResponse, RecipientsGetRecipientData, RecipientsGetRecipientError, RecipientsGetRecipientResponse, RecipientsGetRecipientsError, RecipientsGetRecipientsResponse, RecipientsCreateRecipientData, RecipientsCreateRecipientError, RecipientsCreateRecipientResponse, BanksGetBanksData, BanksGetBanksError, BanksGetBanksResponse, TransfersGetTransfersError, TransfersGetTransfersResponse, TransfersCreateTransferData, TransfersCreateTransferError, TransfersCreateTransferResponse, TransfersGetTransferData, TransfersGetTransferError, TransfersGetTransferResponse, WebhooksEventFromKoyweReceivedError, WebhooksEventFromKoyweReceivedResponse, WebhooksEventFromBridgeReceivedError, WebhooksEventFromBridgeReceivedResponse, WebhooksEventFromAipriseReceivedError, WebhooksEventFromAipriseReceivedResponse, CountriesGetCountriesError, CountriesGetCountriesResponse, UsersGetUserError, UsersGetUserResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Login Or Create
 */
export const loginLoginOrCreate = <ThrowOnError extends boolean = false>(options: Options<LoginLoginOrCreateData, ThrowOnError>) => { return (options?.client ?? client).post<LoginLoginOrCreateResponse, LoginLoginOrCreateError, ThrowOnError>({
    ...options,
    url: '/v0/login_or_create'
}); };

/**
 * Create Quote
 */
export const quotesCreateQuote = <ThrowOnError extends boolean = false>(options: Options<QuotesCreateQuoteData, ThrowOnError>) => { return (options?.client ?? client).post<QuotesCreateQuoteResponse, QuotesCreateQuoteError, ThrowOnError>({
    ...options,
    url: '/v0/quotes/'
}); };

/**
 * Get Quote
 */
export const quotesGetQuote = <ThrowOnError extends boolean = false>(options: Options<QuotesGetQuoteData, ThrowOnError>) => { return (options?.client ?? client).get<QuotesGetQuoteResponse, QuotesGetQuoteError, ThrowOnError>({
    ...options,
    url: '/v0/quotes/{quote_id}'
}); };

/**
 * Get Recipient
 */
export const recipientsGetRecipient = <ThrowOnError extends boolean = false>(options: Options<RecipientsGetRecipientData, ThrowOnError>) => { return (options?.client ?? client).get<RecipientsGetRecipientResponse, RecipientsGetRecipientError, ThrowOnError>({
    ...options,
    url: '/v0/recipients/{recipient_id}'
}); };

/**
 * Get Recipients
 */
export const recipientsGetRecipients = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<RecipientsGetRecipientsResponse, RecipientsGetRecipientsError, ThrowOnError>({
    ...options,
    url: '/v0/recipients/'
}); };

/**
 * Create Recipient
 */
export const recipientsCreateRecipient = <ThrowOnError extends boolean = false>(options: Options<RecipientsCreateRecipientData, ThrowOnError>) => { return (options?.client ?? client).post<RecipientsCreateRecipientResponse, RecipientsCreateRecipientError, ThrowOnError>({
    ...options,
    url: '/v0/recipients/'
}); };

/**
 * Get Banks
 */
export const banksGetBanks = <ThrowOnError extends boolean = false>(options: Options<BanksGetBanksData, ThrowOnError>) => { return (options?.client ?? client).get<BanksGetBanksResponse, BanksGetBanksError, ThrowOnError>({
    ...options,
    url: '/v0/banks/'
}); };

/**
 * Get Transfers
 */
export const transfersGetTransfers = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<TransfersGetTransfersResponse, TransfersGetTransfersError, ThrowOnError>({
    ...options,
    url: '/v0/transfers/'
}); };

/**
 * Create Transfer
 */
export const transfersCreateTransfer = <ThrowOnError extends boolean = false>(options: Options<TransfersCreateTransferData, ThrowOnError>) => { return (options?.client ?? client).post<TransfersCreateTransferResponse, TransfersCreateTransferError, ThrowOnError>({
    ...options,
    url: '/v0/transfers/'
}); };

/**
 * Get Transfer
 */
export const transfersGetTransfer = <ThrowOnError extends boolean = false>(options: Options<TransfersGetTransferData, ThrowOnError>) => { return (options?.client ?? client).get<TransfersGetTransferResponse, TransfersGetTransferError, ThrowOnError>({
    ...options,
    url: '/v0/transfers/{transaction_id}'
}); };

/**
 * Event From Koywe Received
 */
export const webhooksEventFromKoyweReceived = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).post<WebhooksEventFromKoyweReceivedResponse, WebhooksEventFromKoyweReceivedError, ThrowOnError>({
    ...options,
    url: '/v0/webhooks/koywe'
}); };

/**
 * Event From Bridge Received
 */
export const webhooksEventFromBridgeReceived = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).post<WebhooksEventFromBridgeReceivedResponse, WebhooksEventFromBridgeReceivedError, ThrowOnError>({
    ...options,
    url: '/v0/webhooks/bridge'
}); };

/**
 * Event From Aiprise Received
 */
export const webhooksEventFromAipriseReceived = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).post<WebhooksEventFromAipriseReceivedResponse, WebhooksEventFromAipriseReceivedError, ThrowOnError>({
    ...options,
    url: '/v0/webhooks/aiprise'
}); };

/**
 * Get Countries
 */
export const countriesGetCountries = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<CountriesGetCountriesResponse, CountriesGetCountriesError, ThrowOnError>({
    ...options,
    url: '/v0/countries/'
}); };

/**
 * Get User
 * Get current user.
 */
export const usersGetUser = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<UsersGetUserResponse, UsersGetUserError, ThrowOnError>({
    ...options,
    url: '/v0/users/me'
}); };