// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type Options,
} from "@hey-api/client-fetch";
import type {
  AssetsGetAssetDetailData,
  AssetsGetAssetDetailError,
  AssetsGetAssetDetailResponse,
  AssetsGetAssetsError,
  AssetsGetAssetsResponse,
  AssetsGetAssetTicksData,
  AssetsGetAssetTicksError,
  AssetsGetAssetTicksResponse,
  BanksGetBanksData,
  BanksGetBanksError,
  BanksGetBanksResponse,
  CountriesGetCountriesError,
  CountriesGetCountriesResponse,
  LoginLoginOrCreateData,
  LoginLoginOrCreateError,
  LoginLoginOrCreateResponse,
  OrdersCreateQuoteOrderData,
  OrdersCreateQuoteOrderError,
  OrdersCreateQuoteOrderResponse,
  OrdersGetOrdersError,
  OrdersGetOrdersResponse,
  QuotesCreateQuoteData,
  QuotesCreateQuoteError,
  QuotesCreateQuoteResponse,
  QuotesGetQuoteData,
  QuotesGetQuoteError,
  QuotesGetQuoteResponse,
  RecipientsCreateRecipientData,
  RecipientsCreateRecipientError,
  RecipientsCreateRecipientResponse,
  RecipientsGetRecipientData,
  RecipientsGetRecipientError,
  RecipientsGetRecipientResponse,
  RecipientsGetRecipientsError,
  RecipientsGetRecipientsResponse,
  TransfersCreateTransferData,
  TransfersCreateTransferError,
  TransfersCreateTransferResponse,
  TransfersGetTransferData,
  TransfersGetTransferError,
  TransfersGetTransferResponse,
  TransfersGetTransfersError,
  TransfersGetTransfersResponse,
  UsersMeError,
  UsersMeResponse,
  UsersMyAssetsError,
  UsersMyAssetsResponse,
  UsersMyBalanceError,
  UsersMyBalanceResponse,
  WebhooksEventFromAipriseReceivedError,
  WebhooksEventFromAipriseReceivedResponse,
  WebhooksEventFromBridgeReceivedError,
  WebhooksEventFromBridgeReceivedResponse,
  WebhooksEventFromKoyweReceivedError,
  WebhooksEventFromKoyweReceivedResponse,
} from "./types.gen";

export const client = createClient(createConfig());

/**
 * Login Or Create
 */
export const loginLoginOrCreate = <ThrowOnError extends boolean = false>(
  options: Options<LoginLoginOrCreateData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    LoginLoginOrCreateResponse,
    LoginLoginOrCreateError,
    ThrowOnError
  >({
    ...options,
    url: "/v0/login_or_create",
  });
};

/**
 * Create Quote
 */
export const quotesCreateQuote = <ThrowOnError extends boolean = false>(
  options: Options<QuotesCreateQuoteData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    QuotesCreateQuoteResponse,
    QuotesCreateQuoteError,
    ThrowOnError
  >({
    ...options,
    url: "/v0/quotes/",
  });
};

/**
 * Get Quote
 */
export const quotesGetQuote = <ThrowOnError extends boolean = false>(
  options: Options<QuotesGetQuoteData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    QuotesGetQuoteResponse,
    QuotesGetQuoteError,
    ThrowOnError
  >({
    ...options,
    url: "/v0/quotes/{quote_id}",
  });
};

/**
 * Get Recipient
 */
export const recipientsGetRecipient = <ThrowOnError extends boolean = false>(
  options: Options<RecipientsGetRecipientData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    RecipientsGetRecipientResponse,
    RecipientsGetRecipientError,
    ThrowOnError
  >({
    ...options,
    url: "/v0/recipients/{recipient_id}",
  });
};

/**
 * Get Recipients
 */
export const recipientsGetRecipients = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    RecipientsGetRecipientsResponse,
    RecipientsGetRecipientsError,
    ThrowOnError
  >({
    ...options,
    url: "/v0/recipients/",
  });
};

/**
 * Create Recipient
 */
export const recipientsCreateRecipient = <ThrowOnError extends boolean = false>(
  options: Options<RecipientsCreateRecipientData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    RecipientsCreateRecipientResponse,
    RecipientsCreateRecipientError,
    ThrowOnError
  >({
    ...options,
    url: "/v0/recipients/",
  });
};

/**
 * Get Banks
 */
export const banksGetBanks = <ThrowOnError extends boolean = false>(
  options: Options<BanksGetBanksData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    BanksGetBanksResponse,
    BanksGetBanksError,
    ThrowOnError
  >({
    ...options,
    url: "/v0/banks/",
  });
};

/**
 * Get Transfers
 */
export const transfersGetTransfers = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    TransfersGetTransfersResponse,
    TransfersGetTransfersError,
    ThrowOnError
  >({
    ...options,
    url: "/v0/transfers/",
  });
};

/**
 * Create Transfer
 */
export const transfersCreateTransfer = <ThrowOnError extends boolean = false>(
  options: Options<TransfersCreateTransferData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    TransfersCreateTransferResponse,
    TransfersCreateTransferError,
    ThrowOnError
  >({
    ...options,
    url: "/v0/transfers/",
  });
};

/**
 * Get Transfer
 */
export const transfersGetTransfer = <ThrowOnError extends boolean = false>(
  options: Options<TransfersGetTransferData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    TransfersGetTransferResponse,
    TransfersGetTransferError,
    ThrowOnError
  >({
    ...options,
    url: "/v0/transfers/{transaction_id}",
  });
};

/**
 * Event From Koywe Received
 */
export const webhooksEventFromKoyweReceived = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    WebhooksEventFromKoyweReceivedResponse,
    WebhooksEventFromKoyweReceivedError,
    ThrowOnError
  >({
    ...options,
    url: "/v0/webhooks/koywe",
  });
};

/**
 * Event From Bridge Received
 */
export const webhooksEventFromBridgeReceived = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    WebhooksEventFromBridgeReceivedResponse,
    WebhooksEventFromBridgeReceivedError,
    ThrowOnError
  >({
    ...options,
    url: "/v0/webhooks/bridge",
  });
};

/**
 * Event From Aiprise Received
 */
export const webhooksEventFromAipriseReceived = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    WebhooksEventFromAipriseReceivedResponse,
    WebhooksEventFromAipriseReceivedError,
    ThrowOnError
  >({
    ...options,
    url: "/v0/webhooks/aiprise",
  });
};

/**
 * Get Countries
 */
export const countriesGetCountries = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    CountriesGetCountriesResponse,
    CountriesGetCountriesError,
    ThrowOnError
  >({
    ...options,
    url: "/v0/countries/",
  });
};

/**
 * Me
 * Get current user.
 */
export const usersMe = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UsersMeResponse,
    UsersMeError,
    ThrowOnError
  >({
    ...options,
    url: "/v0/users/me",
  });
};

/**
 * My Balance
 */
export const usersMyBalance = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UsersMyBalanceResponse,
    UsersMyBalanceError,
    ThrowOnError
  >({
    ...options,
    url: "/v0/users/me/balance",
  });
};

/**
 * My Assets
 * Get user's stock assets
 */
export const usersMyAssets = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UsersMyAssetsResponse,
    UsersMyAssetsError,
    ThrowOnError
  >({
    ...options,
    url: "/v0/users/me/assets",
  });
};

/**
 * Get Assets
 */
export const assetsGetAssets = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    AssetsGetAssetsResponse,
    AssetsGetAssetsError,
    ThrowOnError
  >({
    ...options,
    url: "/v0/assets/",
  });
};

/**
 * Get Asset Ticks
 */
export const assetsGetAssetTicks = <ThrowOnError extends boolean = false>(
  options: Options<AssetsGetAssetTicksData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    AssetsGetAssetTicksResponse,
    AssetsGetAssetTicksError,
    ThrowOnError
  >({
    ...options,
    url: "/v0/assets/{asset_id}/ticks",
  });
};

/**
 * Get Asset Detail
 */
export const assetsGetAssetDetail = <ThrowOnError extends boolean = false>(
  options: Options<AssetsGetAssetDetailData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    AssetsGetAssetDetailResponse,
    AssetsGetAssetDetailError,
    ThrowOnError
  >({
    ...options,
    url: "/v0/assets/{asset_id}/",
  });
};

/**
 * Get Orders
 */
export const ordersGetOrders = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    OrdersGetOrdersResponse,
    OrdersGetOrdersError,
    ThrowOnError
  >({
    ...options,
    url: "/v0/orders/",
  });
};

/**
 * Create Quote Order
 */
export const ordersCreateQuoteOrder = <ThrowOnError extends boolean = false>(
  options: Options<OrdersCreateQuoteOrderData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    OrdersCreateQuoteOrderResponse,
    OrdersCreateQuoteOrderError,
    ThrowOnError
  >({
    ...options,
    url: "/v0/orders/quote",
  });
};
