// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { LoginLoginOrCreateData, LoginLoginOrCreateError, LoginLoginOrCreateResponse, LoginAuthenticateData, LoginAuthenticateError, LoginAuthenticateResponse, CustomersGetCustomerError, CustomersGetCustomerResponse, CustomersCreateCustomerData, CustomersCreateCustomerError, CustomersCreateCustomerResponse, CustomersGetBalanceError, CustomersGetBalanceResponse, QuotesCreateQuoteData, QuotesCreateQuoteError, QuotesCreateQuoteResponse, QuotesGetQuoteData, QuotesGetQuoteError, QuotesGetQuoteResponse, RecipientsGetRecipientData, RecipientsGetRecipientError, RecipientsGetRecipientResponse, RecipientsGetRecipientsError, RecipientsGetRecipientsResponse, RecipientsCreateRecipientData, RecipientsCreateRecipientError, RecipientsCreateRecipientResponse, BanksGetBanksData, BanksGetBanksError, BanksGetBanksResponse, TransactionsCreateTransactionData, TransactionsCreateTransactionError, TransactionsCreateTransactionResponse, WebhooksNewEventReceivedError, WebhooksNewEventReceivedResponse, CountriesGetCountriesError, CountriesGetCountriesResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Login Or Create
 */
export const loginLoginOrCreate = <ThrowOnError extends boolean = false>(options: Options<LoginLoginOrCreateData, ThrowOnError>) => { return (options?.client ?? client).post<LoginLoginOrCreateResponse, LoginLoginOrCreateError, ThrowOnError>({
    ...options,
    url: '/v0/login_or_create'
}); };

/**
 * Authenticate
 */
export const loginAuthenticate = <ThrowOnError extends boolean = false>(options: Options<LoginAuthenticateData, ThrowOnError>) => { return (options?.client ?? client).post<LoginAuthenticateResponse, LoginAuthenticateError, ThrowOnError>({
    ...options,
    url: '/v0/auth'
}); };

/**
 * Get Customer
 * Get current user.
 */
export const customersGetCustomer = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<CustomersGetCustomerResponse, CustomersGetCustomerError, ThrowOnError>({
    ...options,
    url: '/v0/customers/me'
}); };

/**
 * Create Customer
 */
export const customersCreateCustomer = <ThrowOnError extends boolean = false>(options: Options<CustomersCreateCustomerData, ThrowOnError>) => { return (options?.client ?? client).post<CustomersCreateCustomerResponse, CustomersCreateCustomerError, ThrowOnError>({
    ...options,
    url: '/v0/customers/'
}); };

/**
 * Get Balance
 * Get current user balance.
 */
export const customersGetBalance = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<CustomersGetBalanceResponse, CustomersGetBalanceError, ThrowOnError>({
    ...options,
    url: '/v0/customers/balance'
}); };

/**
 * Create Quote
 */
export const quotesCreateQuote = <ThrowOnError extends boolean = false>(options: Options<QuotesCreateQuoteData, ThrowOnError>) => { return (options?.client ?? client).post<QuotesCreateQuoteResponse, QuotesCreateQuoteError, ThrowOnError>({
    ...options,
    url: '/v0/quotes/'
}); };

/**
 * Get Quote
 */
export const quotesGetQuote = <ThrowOnError extends boolean = false>(options: Options<QuotesGetQuoteData, ThrowOnError>) => { return (options?.client ?? client).get<QuotesGetQuoteResponse, QuotesGetQuoteError, ThrowOnError>({
    ...options,
    url: '/v0/quotes/{quote_id}'
}); };

/**
 * Get Recipient
 */
export const recipientsGetRecipient = <ThrowOnError extends boolean = false>(options: Options<RecipientsGetRecipientData, ThrowOnError>) => { return (options?.client ?? client).get<RecipientsGetRecipientResponse, RecipientsGetRecipientError, ThrowOnError>({
    ...options,
    url: '/v0/recipients/{recipient_id}'
}); };

/**
 * Get Recipients
 */
export const recipientsGetRecipients = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<RecipientsGetRecipientsResponse, RecipientsGetRecipientsError, ThrowOnError>({
    ...options,
    url: '/v0/recipients/'
}); };

/**
 * Create Recipient
 */
export const recipientsCreateRecipient = <ThrowOnError extends boolean = false>(options: Options<RecipientsCreateRecipientData, ThrowOnError>) => { return (options?.client ?? client).post<RecipientsCreateRecipientResponse, RecipientsCreateRecipientError, ThrowOnError>({
    ...options,
    url: '/v0/recipients/'
}); };

/**
 * Get Banks
 */
export const banksGetBanks = <ThrowOnError extends boolean = false>(options: Options<BanksGetBanksData, ThrowOnError>) => { return (options?.client ?? client).get<BanksGetBanksResponse, BanksGetBanksError, ThrowOnError>({
    ...options,
    url: '/v0/banks/'
}); };

/**
 * Create Transaction
 */
export const transactionsCreateTransaction = <ThrowOnError extends boolean = false>(options: Options<TransactionsCreateTransactionData, ThrowOnError>) => { return (options?.client ?? client).post<TransactionsCreateTransactionResponse, TransactionsCreateTransactionError, ThrowOnError>({
    ...options,
    url: '/v0/transactions/'
}); };

/**
 * New Event Received
 */
export const webhooksNewEventReceived = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).post<WebhooksNewEventReceivedResponse, WebhooksNewEventReceivedError, ThrowOnError>({
    ...options,
    url: '/v0/webhooks/koywe'
}); };

/**
 * Get Countries
 */
export const countriesGetCountries = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<CountriesGetCountriesResponse, CountriesGetCountriesError, ThrowOnError>({
    ...options,
    url: '/v0/countries/'
}); };