name: E2E Tests
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  e2e-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: yarn install
        
      - name: Install Maestro
        run: |
          brew tap mobile-dev-inc/tap
          brew install maestro
          
      - name: Build iOS app
        run: yarn ios
        
      - name: Run Maestro tests
        run: yarn test:e2e 